pull_request_rules:
  - name: Ready to merge
    conditions:
      - label=ready-to-merge
      - check-success=Build devcontainer
      - check-success=Run checks
      - check-success~=GitGuardian
    actions:
      merge:
        method: rebase
        rebase_fallback: null
