pull_request_rules:
  - name: Ready to merge
    conditions:
      - label=ready-to-merge
      - check-success=GitBook QA
    actions:
      merge:
        method: rebase
        rebase_fallback: null
